import { chmod, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { execFileSync } from 'node:child_process';
import { describe, expect, it } from 'vitest';
import { CodexAppServerAdapter } from '../src/codex.js';

type Request = { id?: string | number; method?: string; params?: unknown; result?: unknown; error?: { code?: number } };
const officialThread = { id: 'thread-1', sessionId: 'session-1', preview: '', ephemeral: true, modelProvider: 'openai', createdAt: 1, updatedAt: 1, status: { type: 'idle' }, cwd: '/tmp', cliVersion: '0.145.0', source: 'unknown', turns: [] };
const officialTurn = (status: 'inProgress' | 'completed') => ({ id: 'turn-1', items: [], itemsView: 'full', status, error: null, startedAt: 1, completedAt: status === 'completed' ? 2 : null, durationMs: status === 'completed' ? 1_000 : null });
const officialThreadStartResponse = { thread: officialThread, model: 'gpt-5-codex', modelProvider: 'openai', serviceTier: null, cwd: '/tmp', instructionSources: [], approvalPolicy: 'on-request', approvalsReviewer: 'user', sandbox: { type: 'readOnly', networkAccess: false }, reasoningEffort: null };
const officialTurnStartResponse = { turn: officialTurn('inProgress') };
const officialTurnStarted = { threadId: 'thread-1', turn: officialTurn('inProgress') };
const officialTurnCompleted = { threadId: 'thread-1', turn: officialTurn('completed') };
const officialDelta = { threadId: 'thread-1', turnId: 'turn-1', itemId: 'item-1', delta: 'x' };
const officialInitializeResponse = { userAgent: 'codex-test', codexHome: '/tmp', platformFamily: 'unix', platformOs: 'linux' };
const officialLoginResponse = { type: 'chatgptDeviceCode', loginId: 'login-1', verificationUrl: 'https://example.invalid', userCode: 'CODE' };
const officialCancelResponse = { status: 'canceled' };
const officialAccountResponse = { account: { type: 'chatgpt', email: null, planType: 'plus' }, requiresOpenaiAuth: false };
const officialRateLimitsResponse = { rateLimits: { limitId: null, limitName: null, primary: { usedPercent: 10, windowDurationMins: null, resetsAt: 100 }, secondary: { usedPercent: 125, windowDurationMins: null, resetsAt: 200 }, credits: null, individualLimit: null, spendControlReached: null, planType: null, rateLimitReachedType: null }, rateLimitsByLimitId: null, rateLimitResetCredits: null };
const officialModelListResponse = { data: [{ id: 'model-id', model: 'gpt-5-codex', displayName: 'GPT-5 Codex', description: 'fixture', hidden: false, supportedReasoningEfforts: [], defaultReasoningEffort: 'medium', isDefault: true }], nextCursor: null };
const fixtureSource = `#!/usr/bin/env node
if(process.argv.includes('--version')){console.log('codex-cli 0.145.0');process.exit(0)}
const fs=require('node:fs'),path=require('node:path'),log=path.join(__dirname,'requests.jsonl');fs.writeFileSync(path.join(__dirname,'pid'),String(process.pid));
const threadStart=${JSON.stringify(officialThreadStartResponse)},turnStart=${JSON.stringify(officialTurnStartResponse)},turnStarted=${JSON.stringify(officialTurnStarted)},turnCompleted=${JSON.stringify(officialTurnCompleted)},delta=${JSON.stringify(officialDelta)},modelList=${JSON.stringify(officialModelListResponse)};
const rl=require('node:readline').createInterface({input:process.stdin});rl.on('line',line=>{fs.appendFileSync(log,line+'\\n');const r=JSON.parse(line),out=x=>process.stdout.write(JSON.stringify(x)+'\\n');if(r.method==='initialize'){out({jsonrpc:'2.0',id:r.id,result:{...${JSON.stringify(officialInitializeResponse)},codexHome:process.env.CODEX_HOME}});return}if(r.method==='thread/start'){out({jsonrpc:'2.0',id:r.id,result:threadStart});return}if(r.method==='turn/start'){out({jsonrpc:'2.0',id:r.id,result:turnStart});out({jsonrpc:'2.0',method:'turn/started',params:turnStarted});out({jsonrpc:'2.0',method:'item/agentMessage/delta',params:delta});out({jsonrpc:'2.0',id:99,method:'item/commandExecution/requestApproval',params:{threadId:'thread-1',turnId:'turn-1',itemId:'item-2',startedAtMs:0,environmentId:null}});return}if(r.id===99&&r.result){out({jsonrpc:'2.0',method:'turn/completed',params:turnCompleted});return}if(r.method==='account/login/start'){out({jsonrpc:'2.0',id:r.id,result:${JSON.stringify(officialLoginResponse)}});return}if(r.method==='account/login/cancel'){out({jsonrpc:'2.0',id:r.id,result:${JSON.stringify(officialCancelResponse)}});return}if(r.method==='turn/interrupt'){out({jsonrpc:'2.0',id:r.id,result:{}});return}if(r.method==='account/logout'){out({jsonrpc:'2.0',id:r.id,result:{}});return}if(r.method==='account/read'){out({jsonrpc:'2.0',id:r.id,result:${JSON.stringify(officialAccountResponse)}});return}if(r.method==='model/list'){out({jsonrpc:'2.0',id:r.id,result:modelList});return}if(r.method==='account/rateLimits/read'){out({jsonrpc:'2.0',id:r.id,result:${JSON.stringify(officialRateLimitsResponse)}});return}out({jsonrpc:'2.0',id:r.id,result:{}})})`;
async function fixture(source = fixtureSource) { const dir = await mkdtemp(join(tmpdir(), 'patty-rpc-')); const command = join(dir, 'codex'); await writeFile(command, source); await chmod(command, 0o700); return { dir, command }; }
async function requests(dir: string): Promise<Request[]> { const data = await readFile(join(dir, 'requests.jsonl'), 'utf8'); return data.trim() ? data.trim().split('\n').map(line => JSON.parse(line) as Request) : []; }
async function waitForRequest(dir: string, predicate: (request: Request) => boolean) { for (let attempt = 0; attempt < 50; attempt++) { const match = (await requests(dir)).find(predicate); if (match) return match; await new Promise(resolve => setTimeout(resolve, 10)); } throw new Error('fixture request was not observed'); }

async function schema(name: string) { return JSON.parse(await readFile(resolve(import.meta.dirname, `../../../packages/codex-protocol/generated/schemas/${name}.json`), 'utf8')) as object; }

describe('official 0.145.0 app-server contract', () => {
  it('schema-validates and emits exact model-bearing thread and turn payloads', async () => { const { dir, command } = await fixture(); const adapter = new CodexAppServerAdapter(command, [], dir, '0.145.0'); await adapter.start(); const events: string[] = []; await adapter.run(undefined, 'gpt-5-codex', 'x', event => events.push(event.type)); await new Promise(resolve => setTimeout(resolve, 10)); await adapter.approve('99', false); const sent = await requests(dir); const thread = sent.find(request => request.method === 'thread/start')!; const turn = sent.find(request => request.method === 'turn/start')!; const Ajv = (await import('ajv')).default as unknown as new (options: { strict: boolean; validateFormats: boolean }) => { compile: (schema: object) => (data: unknown) => boolean }; const ajv = new Ajv({ strict: false, validateFormats: false }); for (const [name, value] of [['ThreadStartParams', thread.params], ['TurnStartParams', turn.params], ['ThreadStartResponse', officialThreadStartResponse], ['TurnStartResponse', officialTurnStartResponse], ['TurnStartedNotification', officialTurnStarted], ['AgentMessageDeltaNotification', officialDelta], ['TurnCompletedNotification', officialTurnCompleted], ['ModelListResponse', officialModelListResponse]] as const) expect(ajv.compile(await schema(name))(value), name).toBe(true); expect(thread.params).toEqual({ model: 'gpt-5-codex', ephemeral: true }); expect(turn.params).toEqual({ threadId: 'thread-1', model: 'gpt-5-codex', input: [{ type: 'text', text: 'x', text_elements: [] }] }); expect(events).toEqual(['started', 'delta', 'approval_required', 'completed']); await adapter.shutdown(); });
  it('schema-validates exercised login, cancel, account, quota, interrupt, approval, and logout request envelopes', async () => { const { dir, command } = await fixture(); const adapter = new CodexAppServerAdapter(command, [], dir, '0.145.0'); await adapter.start(); await adapter.login('device_code'); await adapter.cancelLogin(); await adapter.snapshot(); await adapter.run(undefined, 'gpt-5-codex', 'x', () => undefined); await adapter.interrupt('turn-1'); await new Promise(resolve => setTimeout(resolve, 10)); await adapter.approve('99', false); await adapter.logout(); const Ajv = (await import('ajv')).default as unknown as new (options: { strict: boolean; validateFormats: boolean }) => { compile: (schema: object) => (data: unknown) => boolean }; const ajv = new Ajv({ strict: false, validateFormats: false }); const sent = await requests(dir); for (const [method, name] of [['initialize','InitializeParams'], ['account/login/start','LoginAccountParams'], ['account/login/cancel','CancelLoginAccountParams'], ['account/read','GetAccountParams'], ['turn/interrupt','TurnInterruptParams']] as const) { const request = sent.find(item => item.method === method); expect(request, `missing ${method}`).toBeTruthy(); expect(ajv.compile(await schema(name))(request!.params), `${method} params`).toBe(true); } for (const method of ['account/rateLimits/read', 'account/logout']) expect(sent.find(item => item.method === method), `missing ${method}`).toMatchObject({ method }); expect(sent.find(item => item.method === 'account/rateLimits/read')).not.toHaveProperty('params'); expect(sent.find(item => item.method === 'account/logout')).not.toHaveProperty('params'); expect(sent.find(item => item.id === 99)?.result).toEqual({ decision: 'decline' }); await adapter.shutdown(); });
  it('schema-validates exact exercised response and approval fixtures', async () => { const Ajv = (await import('ajv')).default as unknown as new (options: { strict: boolean; validateFormats: boolean }) => { compile: (schema: object) => (data: unknown) => boolean }; const ajv = new Ajv({ strict: false, validateFormats: false }); for (const [name, value] of [['InitializeResponse', officialInitializeResponse], ['LoginAccountResponse', officialLoginResponse], ['CancelLoginAccountResponse', officialCancelResponse], ['GetAccountResponse', officialAccountResponse], ['GetAccountRateLimitsResponse', officialRateLimitsResponse], ['TurnInterruptResponse', {}], ['CommandExecutionRequestApprovalResponse', { decision: 'decline' }]] as const) expect(ajv.compile(await schema(name))(value), name).toBe(true); });
  it('uses the most restrictive primary or secondary rate-limit window and its reset', async () => { const secondary = await fixture(); const secondaryAdapter = new CodexAppServerAdapter(secondary.command, [], secondary.dir, '0.145.0'); await secondaryAdapter.start(); const secondarySnapshot = await secondaryAdapter.snapshot(); expect(secondarySnapshot.quota.remaining).toBe(0); expect(secondarySnapshot.quota.resetAt).toBe(new Date(200_000).toISOString()); await secondaryAdapter.shutdown(); const primary = await fixture(fixtureSource.replace('\"usedPercent\":10,\"windowDurationMins\":null,\"resetsAt\":100', '\"usedPercent\":80,\"windowDurationMins\":null,\"resetsAt\":300').replace('\"usedPercent\":125,\"windowDurationMins\":null,\"resetsAt\":200', '\"usedPercent\":20,\"windowDurationMins\":null,\"resetsAt\":400')); const primaryAdapter = new CodexAppServerAdapter(primary.command, [], primary.dir, '0.145.0'); await primaryAdapter.start(); const primarySnapshot = await primaryAdapter.snapshot(); expect(primarySnapshot.quota.remaining).toBeCloseTo(.2); expect(primarySnapshot.quota.resetAt).toBe(new Date(300_000).toISOString()); await primaryAdapter.shutdown(); });
  it('uses the latest reset when restrictive windows tie', async () => { const tied = await fixture(fixtureSource.replace('\"usedPercent\":10,\"windowDurationMins\":null,\"resetsAt\":100', '\"usedPercent\":80,\"windowDurationMins\":null,\"resetsAt\":300').replace('\"usedPercent\":125,\"windowDurationMins\":null,\"resetsAt\":200', '\"usedPercent\":80,\"windowDurationMins\":null,\"resetsAt\":400')); const adapter = new CodexAppServerAdapter(tied.command, [], tied.dir, '0.145.0'); await adapter.start(); expect((await adapter.snapshot()).quota.resetAt).toBe(new Date(400_000).toISOString()); await adapter.shutdown(); });
  it('reproduces the documented canonical schema digest', () => { const source = resolve(import.meta.dirname, '../../../packages/codex-protocol/generated/schemas/codex_app_server_protocol.v2.schemas.json'); const digest = execFileSync(process.execPath, ['scripts/canonical-schema-digest.mjs', source], { cwd: resolve(import.meta.dirname, '../../..'), encoding: 'utf8' }).trim(); const repeat = execFileSync(process.execPath, ['scripts/canonical-schema-digest.mjs', source], { cwd: resolve(import.meta.dirname, '../../..'), encoding: 'utf8' }).trim(); expect(digest).toBe(repeat); expect(digest).toBe('02d8bf6651cd504bff0335f566c011e51ba77c5cc0538cb64ca7ac57739a1597'); });
  it('returns a response for mapped approvals and JSON-RPC method errors for every unsupported id request', async () => { const source = fixtureSource.replace("out({jsonrpc:'2.0',id:99,method:'item/commandExecution/requestApproval'", "out({jsonrpc:'2.0',id:100,method:'item/permissions/requestApproval',params:{threadId:'thread-1',turnId:'turn-1'}});out({jsonrpc:'2.0',id:99,method:'item/commandExecution/requestApproval'"); const { dir, command } = await fixture(source); const adapter = new CodexAppServerAdapter(command, [], dir, '0.145.0'); await adapter.start(); await adapter.run(undefined, 'gpt-5-codex', 'x', () => undefined); await new Promise(resolve => setTimeout(resolve, 10)); await adapter.approve('99', true); expect((await waitForRequest(dir, request => request.id === 99 && request.result !== undefined)).result).toEqual({ decision: 'accept' }); expect((await waitForRequest(dir, request => request.id === 100 && request.error?.code === -32601)).error?.code).toBe(-32601); await adapter.shutdown(); });
  it('associates legacy approval requests queued by conversation before turn/start responds', async () => { const source = fixtureSource.replace("if(r.method==='turn/start'){out({jsonrpc:'2.0',id:r.id,result:turnStart});", "if(r.method==='turn/start'){out({jsonrpc:'2.0',id:77,method:'applyPatchApproval',params:{conversationId:'thread-1',callId:'call-1',fileChanges:{},reason:null,grantRoot:null}});out({jsonrpc:'2.0',id:r.id,result:turnStart});"); const { dir, command } = await fixture(source); const adapter = new CodexAppServerAdapter(command, [], dir, '0.145.0'); await adapter.start(); const events: string[] = []; await adapter.run(undefined, 'gpt-5-codex', 'x', event => events.push(event.type)); expect(events).toContain('approval_required'); await adapter.approve('77', false); expect((await waitForRequest(dir, item => item.id === 77 && item.result !== undefined)).result).toEqual({ decision: 'abort' }); await adapter.shutdown(); });
  it('rejects initialize home mismatch and cleans up the child', async () => { const source = fixtureSource.replace('codexHome:process.env.CODEX_HOME', "codexHome:'/tmp'"); const { dir, command } = await fixture(source); const adapter = new CodexAppServerAdapter(command, [], dir, '0.145.0'); await expect(adapter.start()).rejects.toThrow('protocol_incompatible'); const pid = Number(await readFile(join(dir, 'pid'), 'utf8')); expect(() => process.kill(pid, 0)).toThrow(); });
  it('classifies a nonexistent initialize home as protocol incompatible and cleans up', async () => { const source = fixtureSource.replace('codexHome:process.env.CODEX_HOME', "codexHome:'/definitely/missing-codex-home'"); const { dir, command } = await fixture(source); const adapter = new CodexAppServerAdapter(command, [], dir, '0.145.0'); await expect(adapter.start()).rejects.toThrow('protocol_incompatible'); const pid = Number(await readFile(join(dir, 'pid'), 'utf8')); expect(() => process.kill(pid, 0)).toThrow(); });
  it('cleans up the child after initialize timeout', async () => { const source = fixtureSource.replace("if(r.method==='initialize'){out(", "if(r.method==='initialize'){return}if(false){out("); const { dir, command } = await fixture(source); const adapter = new CodexAppServerAdapter(command, [], dir, '0.145.0', 20); await expect(adapter.start()).rejects.toThrow('rpc timeout'); const pid = Number(await readFile(join(dir, 'pid'), 'utf8')); expect(() => process.kill(pid, 0)).toThrow(); });
  it('rejects a command that is not the pinned official version', async () => { const { dir, command } = await fixture(); await writeFile(command, '#!/bin/sh\necho codex-cli 0.144.0\n'); await chmod(command, 0o700); await expect(new CodexAppServerAdapter(command, [], dir, '0.145.0').start()).rejects.toThrow('protocol_incompatible'); });
});
