import { access, readFile } from 'node:fs/promises';
import { afterEach, describe, expect, it } from 'vitest';
import type { Server } from 'node:http';
import { resolve } from 'node:path';
import { PattyDaemon } from '../src/server.js';
let server: Server | undefined;
afterEach(async () => { await new Promise<void>(resolveClose => server?.close(() => resolveClose()) ?? resolveClose()); server = undefined; });
describe('loopback HTTP API', () => {
  it('requires a local key and creates an idempotent run', async () => { const daemon = new PattyDaemon(); daemon.addFakeAccount('one'); server = await daemon.listen(); const address = server.address() as { port: number }; const url = `http://127.0.0.1:${address.port}`; expect((await fetch(`${url}/v1/accounts`)).status).toBe(401); const headers = { authorization: `Bearer ${daemon.key}`, 'content-type': 'application/json' }; const input = { model: 'gpt-5-codex', input: 'hello', idempotencyKey: 'same' }; const one = await fetch(`${url}/v1/runs`, { method: 'POST', headers, body: JSON.stringify(input) }); expect(one.status).toBe(202); const first = await one.json() as { id: string }; const two = await fetch(`${url}/v1/runs`, { method: 'POST', headers, body: JSON.stringify(input) }); expect((await two.json() as { id: string }).id).toBe(first.id); const conflict = await fetch(`${url}/v1/runs`, { method: 'POST', headers, body: JSON.stringify({ ...input, input: 'different' }) }); expect((await conflict.json() as { error: { code: string } }).error.code).toBe('idempotency_conflict'); });
  it('returns a JSON 404 rather than opening SSE for an unknown run', async () => { const daemon = new PattyDaemon(); server = await daemon.listen(); const address = server.address() as { port: number }; const response = await fetch(`http://127.0.0.1:${address.port}/v1/runs/missing/events`, { headers: { authorization: `Bearer ${daemon.key}` } }); expect(response.status).toBe(404); expect(response.headers.get('content-type')).toContain('application/json'); });
  it('refuses remote binding', () => expect(() => new PattyDaemon().listen(0, '0.0.0.0')).toThrow('loopback'));
  it('publishes the built daemon at the bin target', async () => { const manifest = JSON.parse(await readFile(resolve(import.meta.dirname, '../package.json'), 'utf8')) as { bin: { pattyd: string } }; expect(manifest.bin.pattyd).toBe('./dist/src/main.js'); await expect(access(resolve(import.meta.dirname, '..', manifest.bin.pattyd))).resolves.toBeUndefined(); });
});

describe('SSE lifecycle', () => {
  it('retains terminal events and closes the stream', async () => { const daemon = new PattyDaemon(); daemon.addFakeAccount('one'); server = await daemon.listen(); const port = (server.address() as { port: number }).port; const headers = { authorization: `Bearer ${daemon.key}`, 'content-type': 'application/json' }; const created = await fetch(`http://127.0.0.1:${port}/v1/runs`, { method: 'POST', headers, body: JSON.stringify({ model: 'gpt-5-codex', input: 'x' }) }); const { id } = await created.json() as { id: string }; await new Promise(resolve => setTimeout(resolve, 10)); const stream = await fetch(`http://127.0.0.1:${port}/v1/runs/${id}/events`, { headers }); const text = await stream.text(); expect(text).toContain('id: 1'); expect(text).toContain('"type":"completed"'); });
});

it('returns an allowlisted public run DTO', async () => { const daemon = new PattyDaemon(); const account = daemon.addFakeAccount('dto'); server = await daemon.listen(); const port = (server.address() as {port:number}).port; const headers={authorization:`Bearer ${daemon.key}`,'content-type':'application/json'}; const created=await fetch(`http://127.0.0.1:${port}/v1/runs`,{method:'POST',headers,body:JSON.stringify({model:'gpt-5-codex',input:'secret'})}); const {id}=await created.json() as {id:string}; const dto=await (await fetch(`http://127.0.0.1:${port}/v1/runs/${id}`,{headers})).json() as Record<string,unknown>; expect(dto).toHaveProperty('id'); expect(dto).not.toHaveProperty('provider_turn_id'); expect(dto).not.toHaveProperty('fingerprint'); expect(dto).not.toHaveProperty('idempotency_key'); });

it('uses strict method dispatch and validates thread turns', async () => { const daemon = new PattyDaemon(); daemon.addFakeAccount('strict'); server = await daemon.listen(); const port=(server.address() as {port:number}).port; const headers={authorization:`Bearer ${daemon.key}`,'content-type':'application/json'}; expect((await fetch(`http://127.0.0.1:${port}/v1/runs`,{method:'GET',headers})).status).toBe(404); const thread=await (await fetch(`http://127.0.0.1:${port}/v1/threads`,{method:'POST',headers,body:JSON.stringify({model:'gpt-5-codex'})})).json() as {threadId:string}; expect((await fetch(`http://127.0.0.1:${port}/v1/threads/${thread.threadId}/turns`,{method:'POST',headers,body:JSON.stringify({model:'gpt-5-codex',input:''})})).status).toBe(400); expect((await fetch(`http://127.0.0.1:${port}/v1/threads/${thread.threadId}/turns`,{method:'GET',headers})).status).toBe(405); });
it('rejects cancellation of a terminal run', async () => { const daemon=new PattyDaemon(); daemon.addFakeAccount('terminal'); server=await daemon.listen(); const port=(server.address() as {port:number}).port;const headers={authorization:`Bearer ${daemon.key}`,'content-type':'application/json'};const run=await (await fetch(`http://127.0.0.1:${port}/v1/runs`,{method:'POST',headers,body:JSON.stringify({model:'gpt-5-codex',input:'x'})})).json() as {id:string};await new Promise(resolve=>setTimeout(resolve,10));expect((await fetch(`http://127.0.0.1:${port}/v1/runs/${run.id}/cancel`,{method:'POST',headers})).status).toBe(409); });

it('emits executable Node shebangs for both packaged entrypoints', async () => { const daemonEntry=await readFile(resolve(import.meta.dirname,'../dist/src/main.js'),'utf8'); const cliEntry=await readFile(resolve(import.meta.dirname,'../../cli/dist/index.js'),'utf8'); expect(daemonEntry.startsWith('#!/usr/bin/env node')).toBe(true); expect(cliEntry.startsWith('#!/usr/bin/env node')).toBe(true); });

it('accepts only GET health checks', async () => { const daemon=new PattyDaemon(); server=await daemon.listen(); const port=(server.address() as {port:number}).port; expect((await fetch(`http://127.0.0.1:${port}/healthz`)).status).toBe(200); expect((await fetch(`http://127.0.0.1:${port}/healthz`,{method:'POST'})).status).toBe(405); });

it('rejects non-boolean approval decisions', async () => { const daemon=new PattyDaemon();daemon.addFakeAccount('approval');server=await daemon.listen();const port=(server.address() as {port:number}).port;const headers={authorization:`Bearer ${daemon.key}`,'content-type':'application/json'};const response=await fetch(`http://127.0.0.1:${port}/v1/runs/nope/approvals/a`,{method:'POST',headers,body:JSON.stringify({approved:'false'})});expect(response.status).toBe(400); });

it('exposes authenticated models and router status', async () => { const daemon=new PattyDaemon();daemon.addFakeAccount('pool');server=await daemon.listen();const port=(server.address() as {port:number}).port;const headers={authorization:`Bearer ${daemon.key}`};expect((await fetch(`http://127.0.0.1:${port}/v1/models`,{headers})).status).toBe(200);expect((await fetch(`http://127.0.0.1:${port}/v1/router/status`,{headers})).status).toBe(200); });
